"""order and products

Revision ID: ecc16a62c5d9
Revises: 40e7a2a0d116
Create Date: 2023-12-24 20:28:04.961406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecc16a62c5d9'
down_revision: Union[str, None] = '40e7a2a0d116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('sex', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('remain', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.add_column('users', sa.Column('number', sa.String(), nullable=False))
    op.add_column('users', sa.Column('subscribed', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'users', ['number'])
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'subscribed')
    op.drop_column('users', 'number')
    op.drop_table('orders')
    op.drop_table('products')
    # ### end Alembic commands ###
